[tool.poetry]
name = "ai-car-assistant"
version = "0.1.0"
description = ""
authors = ["Daniel B"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
